# Generated by Django 4.2.3 on 2023-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('MP', 'Mercado Pago')], max_length=2),
        ),
    ]
